apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- producer-football-ncaa-deployment.yaml
- producer-football-ncaa-service.yaml
- servicemonitor.yaml
- scaledobject.yaml
- row-count-cronjob.yaml