apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- traefik-helmrepository.yaml
- ../../../app/base/traefik
- prometheus-helmrepository.yaml
- ../../../app/base/monitoring/prometheus
- ../../../app/base/monitoring/tempo
- grafana-helmrepository.yaml
- ../../../app/base/logging/loki
- stakater-helmrepository.yaml
- ../../../app/base/reloader
- kubernetes-dashboard-helmrepository.yaml
- ../../../app/base/dashboard