apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- traefik-helmrepository.yaml
- ../../../app/base/traefik
- prometheus-helmrepository.yaml
- ../../../app/base/monitoring/prometheus