apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-internal-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: (Host(`api-int.sportdeets.com`) || Host(`67.7.88.82`) || Host(`api.sportdeets.com`)) && !PathPrefix(`/.well-known/acme-challenge/`)
      kind: Rule
      services:
        - name: api-service
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.sportdeets.com`) || Host(`api-int.sportdeets.com`)
      kind: Rule
      services:
        - name: api-service
          port: 8080
  tls:
    secretName: api-sportdeets-tls
