apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/analytics`)
      kind: Rule
      middlewares:
        - name: umami-strip-prefix
      services:
        - name: umami
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/analytics`)
      kind: Rule
      middlewares:
        - name: umami-strip-prefix
      services:
        - name: umami
          port: 3000
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: umami-strip-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /analytics
