---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/grafana`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/grafana`)
      kind: Rule
      middlewares:
        - name: grafana-cors
        - name: grafana-custom-headers
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    secretName: admin-sportdeets-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-custom-headers
  namespace: monitoring
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "admin.sportdeets.com"
      X-Forwarded-Port: "443"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-cors
  namespace: monitoring
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
      - DELETE
      - PATCH
    accessControlAllowOriginListRegex:
      - ".*"
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-headers
  namespace: monitoring
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "grafana.sportdeets.com"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-subdomain
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.sportdeets.com`)
      kind: Rule
      middlewares:
        - name: grafana-headers
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/prometheus`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: kube-prometheus-stack-kps-prometheus
          port: 9090
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-https
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/prometheus`)
      kind: Rule
      middlewares:
        - name: prometheus-stripprefix
      services:
        - name: kube-prometheus-stack-kps-prometheus
          port: 9090
  tls:
    secretName: admin-sportdeets-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-stripprefix
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
      - /prometheus
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager-http
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/alertmanager`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: kube-prometheus-stack-kps-alertmanager
          port: 9093
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager-https
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/alertmanager`)
      kind: Rule
      middlewares:
        - name: alertmanager-stripprefix
      services:
        - name: kube-prometheus-stack-kps-alertmanager
          port: 9093
  tls:
    secretName: admin-sportdeets-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: alertmanager-stripprefix
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
      - /alertmanager
