apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helmrelease.yaml
  - configmap.yaml
  - ingressroutes.yaml
  - pushgateway.yaml
  - dashboard-row-counts.yaml
  - dashboard-rabbitmq.yaml
  - dashboard-rabbitmq-queues.yaml
  - dashboard-historical-sourcing-sagas.yaml
