apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seq-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`admin.sportdeets.com`) && PathPrefix(`/seq`)
      kind: Rule
      services:
        - name: seq
          port: 80
      middlewares:
        - name: seq-stripprefix

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: seq-stripprefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /seq
