apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: seq-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`logging.sportdeets.com`)
      kind: Rule
      services:
        - name: seq
          namespace: default
          port: 80
